"""Build nplex-content.js for the student web app.

Reads:
  content/*/units-*.json   study units (array of unit objects)
  content/*/cases-*.json   course cases (array of case objects)
  content/batch1/*.json    Week 0 diagnostic cases

Runs balance_keys.balance() on the course cases and, separately, on the
diagnostic cases, then writes nplex-content.js defining:
  window.NPLEX_UNITS       object keyed by unit id
  window.NPLEX_CASES       array of course cases
  window.NPLEX_DIAGNOSTIC  array of diagnostic cases
  window.NPLEX_BUILT       ISO date of the build

Files that fail to parse are skipped with a warning so a half-written file
from another writer never breaks the bundle.

Usage: python3 tools/build_bundle.py
"""
import datetime
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from balance_keys import balance  # noqa: E402


def load(path):
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError) as e:
        print(f"  skip {os.path.relpath(path, ROOT)}: {e}", file=sys.stderr)
        return []
    if not isinstance(data, list):
        print(f"  skip {os.path.relpath(path, ROOT)}: not a JSON array", file=sys.stderr)
        return []
    return data


def valid_case(c):
    qs = c.get("questions")
    if not isinstance(qs, list) or not qs:
        return False
    for q in qs:
        if len(q.get("options", [])) != 4 or len(q.get("whyNot", [])) != 4:
            return False
        if not isinstance(q.get("answer"), int) or not 0 <= q["answer"] < 4:
            return False
    return True


def collect(pattern):
    out, seen = [], set()
    for path in sorted(glob.glob(os.path.join(ROOT, pattern))):
        for item in load(path):
            if not isinstance(item, dict) or "id" not in item:
                continue
            if item["id"] in seen:
                print(f"  duplicate id {item['id']} in {os.path.relpath(path, ROOT)}, keeping first", file=sys.stderr)
                continue
            seen.add(item["id"])
            out.append(item)
    return out


def main():
    units = {u["id"]: u for u in collect("content/*/units-*.json")}

    cases = [c for c in collect("content/*/cases-*.json") if valid_case(c)]
    diag = [c for c in collect("content/batch1/*.json") if valid_case(c)]

    if cases:
        balance(cases, seed=2026)
    if diag:
        balance(diag, seed=2027)

    built = datetime.date.today().isoformat()
    js = [
        "/* GENERATED by tools/build_bundle.py. Do not hand-edit; edit content/ and rebuild. */",
        "window.NPLEX_UNITS = " + json.dumps(units, ensure_ascii=False, separators=(",", ":")) + ";",
        "window.NPLEX_CASES = " + json.dumps(cases, ensure_ascii=False, separators=(",", ":")) + ";",
        "window.NPLEX_DIAGNOSTIC = " + json.dumps(diag, ensure_ascii=False, separators=(",", ":")) + ";",
        "window.NPLEX_BUILT = " + json.dumps(built) + ";",
        "",
    ]
    with open(os.path.join(ROOT, "nplex-content.js"), "w", encoding="utf-8") as f:
        f.write("\n".join(js))

    nq = sum(len(c["questions"]) for c in cases)
    nd = sum(len(c["questions"]) for c in diag)
    print(f"units {len(units)}, cases {len(cases)} ({nq} questions), "
          f"diagnostic {len(diag)} cases ({nd} questions), built {built}")


if __name__ == "__main__":
    main()
